version: "3"
services:
  frontend:
    build: ./frontend
    image: my-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
